# Generated by Django 4.2.5 on 2023-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_ingredient_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="dishes",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="restaurant.ingredient"
            ),
        ),
    ]
