# Generated by Django 4.2.5 on 2023-10-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_remove_ingredient_dishes_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_types",
                to="restaurant.dishtype",
            ),
        ),
    ]
